"use client";

import { useEffect, useState } from "react";
import { authHeaders, clientApi } from "@/lib/client-api";

type Audit = { id: string; createdAt: string; action: string; entityType: string; entityId: string | null; ipAddress: string | null; metadata: Record<string, unknown> | null; user: { email: string; name: string; role: string } | null };
const entityOptions = [["", "Все сущности"], ["User", "Пользователь"], ["Vehicle", "Автомобиль"], ["Order", "Заказ"], ["Lead", "Заявка"], ["Settings", "Настройки"], ["Media", "Медиа"]];
const actionOptions = [["", "Все действия"], ["LOGIN", "Вход"], ["CREATE", "Создание"], ["UPDATE", "Изменение"], ["DELETE", "Удаление"], ["STATUS_CHANGE", "Смена статуса"], ["UPDATE_PRICING", "Расчёт"], ["CONVERT_TO_ORDER", "Конвертация"], ["ADD_TIMELINE", "Timeline"]];

export default function AuditPage() {
  const [items, setItems] = useState<Audit[]>([]); const [entityType, setEntityType] = useState(""); const [action, setAction] = useState(""); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1); const [loading, setLoading] = useState(true); const token = typeof window !== "undefined" ? localStorage.getItem("token") : null;
  async function load(nextPage = page) { setLoading(true); const query = new URLSearchParams({ page: String(nextPage), limit: "30" }); if (entityType) query.set("entityType", entityType); if (action) query.set("action", action); const { data } = await clientApi<{ data: Audit[]; meta?: { page: number; totalPages: number } }>(`/api/admin/audit?${query}`, { headers: authHeaders(token) }); setItems(data?.data ?? []); setPage(data?.meta?.page ?? nextPage); setTotalPages(data?.meta?.totalPages ?? 1); setLoading(false); }
  // Protected data is loaded once on the client after the auth token is available.
  // eslint-disable-next-line react-hooks/exhaustive-deps, react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, []);
  return <main className="admin-shell"><header className="admin-top"><div><p className="eyebrow">АДМИН / КОНТРОЛЬ</p><h1>Аудит</h1></div><span className="lead-count">страница {page} / {totalPages}</span></header><section className="audit-content"><div className="audit-toolbar"><select value={entityType} onChange={(event) => setEntityType(event.target.value)}>{entityOptions.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><select value={action} onChange={(event) => setAction(event.target.value)}>{actionOptions.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><button className="button button-red" onClick={() => void load(1)}>Фильтр</button><button className="button button-ghost" onClick={() => { setEntityType(""); setAction(""); void load(1); }}>Сбросить</button></div>{loading ? <p className="admin-empty">Загружаем журнал...</p> : items.length === 0 ? <p className="admin-empty">Событий нет.</p> : <div className="audit-list">{items.map((item) => <article className="audit-card" key={item.id}><div><strong>{item.action}</strong><span>{item.entityType}{item.entityId ? ` / ${item.entityId}` : ""}</span></div><p>{item.user?.name ?? "Система"} · {item.user?.role ?? "SYSTEM"}</p><time>{new Date(item.createdAt).toLocaleString("ru-RU")}{item.ipAddress ? ` · ${item.ipAddress}` : ""}</time>{item.metadata && <pre>{JSON.stringify(item.metadata, null, 2)}</pre>}</article>)}</div>}<div className="audit-pagination"><button className="button button-ghost" disabled={page <= 1 || loading} onClick={() => void load(page - 1)}>← Назад</button><span>{page} / {totalPages}</span><button className="button button-ghost" disabled={page >= totalPages || loading} onClick={() => void load(page + 1)}>Далее →</button></div></section></main>;
}
