"use client";

import { FormEvent, useEffect, useState } from "react";
import { authHeaders, clientApi } from "@/lib/client-api";

type SettingsForm = { defaultCommission: number; currencyRates: { JPY: number; KRW: number; CNY: number }; companyPhone: string; companyEmail: string; companyTelegram: string; companyAddress: string; workingHours: string; siteTitle: string; siteDescription: string };
const empty: SettingsForm = { defaultCommission: 50000, currencyRates: { JPY: 0.62, KRW: 0.069, CNY: 12.8 }, companyPhone: "", companyEmail: "", companyTelegram: "", companyAddress: "", workingHours: "", siteTitle: "ЗаказАвто", siteDescription: "" };

export default function SettingsPage() {
  const [form, setForm] = useState(empty); const [status, setStatus] = useState(""); const [loading, setLoading] = useState(true); const token = typeof window !== "undefined" ? localStorage.getItem("token") : null;
  useEffect(() => { void (async () => { const { data, error } = await clientApi<{ data?: SettingsForm }>("/api/admin/settings", { headers: authHeaders(token) }); if (data?.data) setForm({ ...empty, ...data.data }); if (error) setStatus(error); setLoading(false); })(); }, [token]);
  function update(key: keyof SettingsForm, value: string) { setForm((current) => ({ ...current, [key]: value })); }
  function updateRate(key: keyof SettingsForm["currencyRates"], value: string) { setForm((current) => ({ ...current, currencyRates: { ...current.currencyRates, [key]: Number(value) } })); }
  async function submit(event: FormEvent) { event.preventDefault(); setStatus(""); const { response, error } = await clientApi("/api/admin/settings", { method: "PATCH", headers: authHeaders(token, true), body: JSON.stringify(form) }); setStatus(response.ok ? "Настройки сохранены" : error ?? "Не удалось сохранить настройки"); }
  if (loading) return <main className="admin-loading">Загружаем настройки...</main>;
  return <main className="admin-shell"><header className="admin-top"><div><p className="eyebrow">АДМИН / КОНФИГУРАЦИЯ</p><h1>Настройки</h1></div></header><section className="settings-content"><form className="settings-form" onSubmit={submit}><div className="settings-section"><p className="eyebrow">01 / ФИНАНСЫ</p><h2>Курсы и комиссия</h2><p>Эти значения используются финансовым движком при расчёте итоговой стоимости.</p><div className="settings-fields"><label>Комиссия, ₽<input type="number" min="0" step="0.01" value={form.defaultCommission} onChange={(event) => update("defaultCommission", event.target.value)} /></label>{(["JPY", "KRW", "CNY"] as const).map((currency) => <label key={currency}>Курс {currency} к ₽<input type="number" min="0" step="0.000001" value={form.currencyRates[currency]} onChange={(event) => updateRate(currency, event.target.value)} /></label>)}</div></div><div className="settings-section"><p className="eyebrow">02 / КОНТАКТЫ</p><h2>Данные компании</h2><div className="settings-fields"><label>Телефон<input value={form.companyPhone} onChange={(event) => update("companyPhone", event.target.value)} /></label><label>Email<input type="email" value={form.companyEmail} onChange={(event) => update("companyEmail", event.target.value)} /></label><label>Telegram<input value={form.companyTelegram} onChange={(event) => update("companyTelegram", event.target.value)} /></label><label>Режим работы<input value={form.workingHours} onChange={(event) => update("workingHours", event.target.value)} /></label><label className="settings-wide">Адрес<input value={form.companyAddress} onChange={(event) => update("companyAddress", event.target.value)} /></label></div></div><div className="settings-section"><p className="eyebrow">03 / SEO</p><h2>Описание сайта</h2><div className="settings-fields"><label>Название сайта<input value={form.siteTitle} onChange={(event) => update("siteTitle", event.target.value)} /></label><label className="settings-wide">Описание<input value={form.siteDescription} onChange={(event) => update("siteDescription", event.target.value)} /></label></div></div><div className="settings-actions"><button className="button button-red">Сохранить настройки</button>{status && <span>{status}</span>}</div></form></section></main>;
}
