"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { authHeaders, clientApi } from "@/lib/client-api";

type Order = { id: string; orderNumber: string; trackingToken: string; status: string; createdAt: string; client: { name: string; phone: string | null; email: string | null }; vehicle: { make: string; model: string; year: number } | null };
const statuses = [["NEW", "Новая"], ["IN_PROGRESS", "В работе"], ["VEHICLE_FOUND", "Автомобиль найден"], ["INSPECTION_SCHEDULED", "Проверка назначена"], ["INSPECTION_COMPLETED", "Проверка завершена"], ["REPORT_PROVIDED", "Отчёт отправлен"], ["AWAITING_CLIENT_APPROVAL", "Ожидает решения"], ["APPROVED", "Одобрено"], ["VEHICLE_PURCHASED", "Автомобиль выкуплен"], ["PREPARATION_FOR_SHIPPING", "Подготовка к отправке"], ["IN_TRANSIT", "В пути"], ["ARRIVED_VLADIVOSTOK", "Во Владивостоке"], ["CUSTOMS_CLEARANCE", "Таможня"], ["DELIVERY_RUSSIA", "Доставка по РФ"], ["READY_FOR_PICKUP", "Готов к выдаче"], ["DELIVERED", "Выдан"], ["COMPLETED", "Завершён"], ["CANCELLED", "Отменён"]] as const;

export default function OrdersPage() {
  const [orders, setOrders] = useState<Order[]>([]); const [filter, setFilter] = useState("ALL"); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true); const token = typeof window !== "undefined" ? localStorage.getItem("token") : null;
  async function load() { const { data, error } = await clientApi<{ data: Order[] }>("/api/admin/orders", { headers: authHeaders(token) }); setOrders(data?.data ?? []); if (error) setMessage(error); setLoading(false); }
  // Protected data is loaded once after the client token becomes available.
  // eslint-disable-next-line react-hooks/exhaustive-deps, react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, []);
  async function updateStatus(order: Order, status: string) { const comment = window.prompt("Комментарий к изменению статуса (необязательно):") ?? undefined; const { response, error } = await clientApi("/api/admin/orders", { method: "PATCH", headers: authHeaders(token, true), body: JSON.stringify({ id: order.id, status, comment }) }); setMessage(response.ok ? `Статус ${order.orderNumber} обновлён` : error ?? "Не удалось обновить статус"); if (response.ok) await load(); }
  async function copyTracking(tokenValue: string) { const url = `${window.location.origin}/orders/track/${encodeURIComponent(tokenValue)}`; try { await navigator.clipboard.writeText(url); setMessage("Tracking-ссылка скопирована"); } catch { setMessage(`Tracking-ссылка: ${url}`); } }
  const visible = filter === "ALL" ? orders : orders.filter((order) => order.status === filter);
  return <main className="admin-shell"><header className="admin-top"><div><p className="eyebrow">АДМИН / ПРОЦЕСС</p><h1>Заказы</h1></div><span className="lead-count">{visible.length} заказов</span></header><section className="orders-content"><div className="orders-toolbar"><select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="ALL">Все статусы</option>{statuses.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><button className="button button-ghost" onClick={() => void load()}>Обновить ↻</button></div>{message && <p className="admin-message">{message}</p>}{loading ? <p className="admin-empty">Загружаем заказы...</p> : visible.length === 0 ? <p className="admin-empty">Заказов с таким статусом нет.</p> : <div className="orders-list">{visible.map((order) => <article className="order-admin-card" key={order.id}><div className="order-card-top"><strong><Link href={`/admin/orders/${order.id}`}>{order.orderNumber}</Link></strong><time>{new Date(order.createdAt).toLocaleDateString("ru-RU")}</time></div><div className="order-card-body"><div><h2>{order.client.name}</h2><div className="lead-contacts">{order.client.phone && <a href={`tel:${order.client.phone}`}>{order.client.phone}</a>}{order.client.email && <a href={`mailto:${order.client.email}`}>{order.client.email}</a>}</div>{order.vehicle && <p className="lead-vehicle">{order.vehicle.make} {order.vehicle.model}, {order.vehicle.year}</p>}</div><div className="order-actions"><label>Статус<select value={order.status} onChange={(event) => void updateStatus(order, event.target.value)}>{statuses.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><button className="button button-ghost" onClick={() => void copyTracking(order.trackingToken)}>Скопировать tracking</button></div></div></article>)}</div>}</section></main>;
}
